name: serialport_plus
description: Serial Port plugin for Android devices.
version: 0.1.0
homepage: https://saeedqasemi.ir
repository: https://github.com/sgsm74/serialport_plus

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: '>=2.0.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.serialportplus.serialport_plus
        pluginClass: SerialportPlusPlugin
